apiVersion: v1
kind: Pod
metadata:
  name: morgan-pod
  labels:
    app: morgan-pod
spec:
  containers:
  - name: morgan-pod
    image: 595312265488.dkr.ecr.us-east-1.amazonaws.com/ascending:morgan_31bd664d